import { jsPDF } from 'jspdf';
import { formatHKD } from './format';
import autoTable from 'jspdf-autotable';

export interface PDFData {
  // Mittente (from settings)
  teacherName: string;
  teacherAddress: string;
  teacherEmail?: string;
  teacherPhone?: string;
  brNumber?: string | null;
  bankDetails?: string | null;

  // Cliente
  customerName: string;
  customerAddress?: string | null;
  customerContact?: string | null;

  // Fattura
  invoiceNumber: string;
  issueDate: string;
  dueDate: string;
  subtotal: number;
  discountPercent: number;
  discountAmount: number;
  total: number;
  paymentTerms?: string | null;
  notes?: string | null;

  // Items
  items: {
    description: string;
    lesson_date: string | null;
    hours: number;
    rate: number;
    amount: number;
  }[];

  // Lingua
  language: 'it' | 'en';
}

const labels = {
  it: {
    invoice: 'FATTURA',
    from: 'Mittente',
    to: 'Destinatario',
    br: 'BR Number',
    invoiceNo: 'N. Fattura',
    date: 'Data',
    dueDate: 'Scadenza',
    description: 'Descrizione',
    lessonDate: 'Data lezione',
    hours: 'Ore',
    rate: 'Tariffa (HKD)',
    amount: 'Importo (HKD)',
    subtotal: 'Subtotale',
    discount: 'Sconto',
    total: 'TOTALE',
    paymentTerms: 'Termini di pagamento',
    bankDetails: 'Coordinate bancarie',
    notes: 'Note',
    page: 'Pagina',
    generated: 'Documento generato da HK Invoice Manager',
  },
  en: {
    invoice: 'INVOICE',
    from: 'From',
    to: 'To',
    br: 'BR Number',
    invoiceNo: 'Invoice No.',
    date: 'Date',
    dueDate: 'Due Date',
    description: 'Description',
    lessonDate: 'Lesson Date',
    hours: 'Hours',
    rate: 'Rate (HKD)',
    amount: 'Amount (HKD)',
    subtotal: 'Subtotal',
    discount: 'Discount',
    total: 'TOTAL',
    paymentTerms: 'Payment Terms',
    bankDetails: 'Bank Details',
    notes: 'Notes',
    page: 'Page',
    generated: 'Document generated by HK Invoice Manager',
  },
};

export interface MonthlyReportData {
  teacherName: string;
  teacherAddress: string;
  teacherEmail?: string;
  month: string; // YYYY-MM
  rows: { invoiceNumber: string; customerName: string; issueDate: string; total: number; status: string }[];
  totalRevenue: number;
  totalCount: number;
}

export function generateMonthlyReport(data: MonthlyReportData, language: 'it' | 'en'): jsPDF {
  const l = labels[language];
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });

  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(language === 'it' ? 'REPORT MENSILE' : 'MONTHLY REPORT', 20, 25);
  doc.setDrawColor(26, 115, 232);
  doc.setLineWidth(0.5);
  doc.line(20, 30, 190, 30);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text(language === 'it' ? 'Periodo:' : 'Period:', 20, 40);
  doc.setFont('helvetica', 'normal');
  doc.text(data.month, 50, 40);

  doc.setFont('helvetica', 'bold');
  doc.text(language === 'it' ? 'Insegnante:' : 'Teacher:', 20, 47);
  doc.setFont('helvetica', 'normal');
  doc.text(data.teacherName, 50, 47);

  const tHeaders = [l.invoiceNo, language === 'it' ? 'Cliente' : 'Customer', l.date, l.total, language === 'it' ? 'Stato' : 'Status'];
  const tRows = data.rows.map(r => [r.invoiceNumber, r.customerName, r.issueDate, formatHKD(r.total), r.status]);

  autoTable(doc, {
    startY: 60,
    head: [tHeaders],
    body: tRows,
    theme: 'grid',
    headStyles: { fillColor: [26, 115, 232], textColor: 255, fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fontSize: 8 },
    margin: { left: 20, right: 20 },
  });

  const finalY = (doc as any).lastAutoTable.finalY + 15;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(language === 'it' ? 'TOTALE ENTRATE:' : 'TOTAL REVENUE:', 110, finalY);
  doc.text(formatHKD(data.totalRevenue), 190, finalY, { align: 'right' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(
    language === 'it' ? `Fatture incluse: ${data.totalCount}` : `Invoices included: ${data.totalCount}`,
    110, finalY + 7
  );

  doc.setFontSize(7);
  doc.setFont('helvetica', 'italic');
  doc.text(language === 'it' ? 'Report generato da HK Invoice Manager' : 'Report generated by HK Invoice Manager', 105, 290, { align: 'center' });

  return doc;
}

export function generatePDF(data: PDFData): jsPDF {
  const l = labels[data.language];
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });

  // --- Header ---
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(l.invoice, 20, 25);

  // Line separator
  doc.setDrawColor(26, 115, 232);
  doc.setLineWidth(0.5);
  doc.line(20, 30, 190, 30);

  // --- Mittente (left) ---
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text(l.from + ':', 20, 40);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(data.teacherName, 20, 47);
  doc.setFontSize(8);
  if (data.teacherAddress) doc.text(data.teacherAddress, 20, 53);
  if (data.teacherEmail) doc.text(data.teacherEmail, 20, 59);
  if (data.teacherPhone) doc.text(data.teacherPhone, 20, 65);
  if (data.brNumber) {
    doc.setFont('helvetica', 'bold');
    doc.text(`${l.br}: ${data.brNumber}`, 20, 73);
    doc.setFont('helvetica', 'normal');
  }

  // --- Destinatario (right) ---
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text(l.to + ':', 120, 40);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(data.customerName, 120, 47);
  doc.setFontSize(8);
  if (data.customerAddress) doc.text(data.customerAddress, 120, 53);
  if (data.customerContact) doc.text(data.customerContact, 120, 59);

  // --- Metadata (right aligned) ---
  const metaX = 120;
  let metaY = 80;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text(`${l.invoiceNo}:`, metaX, metaY);
  doc.setFont('helvetica', 'normal');
  doc.text(data.invoiceNumber, metaX + 30, metaY);
  metaY += 6;
  doc.setFont('helvetica', 'bold');
  doc.text(`${l.date}:`, metaX, metaY);
  doc.setFont('helvetica', 'normal');
  doc.text(data.issueDate, metaX + 30, metaY);
  metaY += 6;
  doc.setFont('helvetica', 'bold');
  doc.text(`${l.dueDate}:`, metaX, metaY);
  doc.setFont('helvetica', 'normal');
  doc.text(data.dueDate, metaX + 30, metaY);

  // --- Items Table ---
  const tableHeaders = [
    l.description,
    l.lessonDate,
    l.hours,
    l.rate,
    l.amount,
  ];

  const tableRows = data.items.map(item => [
    item.description,
    item.lesson_date || '-',
    item.hours.toString(),
    item.rate.toFixed(2),
    item.amount.toFixed(2),
  ]);

  autoTable(doc, {
    startY: 100,
    head: [tableHeaders],
    body: tableRows,
    theme: 'grid',
    headStyles: {
      fillColor: [26, 115, 232],
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 9,
    },
    bodyStyles: { fontSize: 8 },
    columnStyles: {
      0: { cellWidth: 70 },
      1: { cellWidth: 30 },
      2: { cellWidth: 20, halign: 'right' },
      3: { cellWidth: 30, halign: 'right' },
      4: { cellWidth: 30, halign: 'right' },
    },
    margin: { left: 20, right: 20 },
  });

  // --- Totals ---
  const finalY = (doc as any).lastAutoTable.finalY + 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`${l.subtotal}:`, 110, finalY);
  doc.text(formatHKD(data.subtotal), 190, finalY, { align: 'right' });

  if (data.discountPercent > 0) {
    const discountY = finalY + 7;
    doc.text(`${l.discount} (${data.discountPercent}%):`, 110, discountY);
    doc.text(`-${formatHKD(data.discountAmount)}`, 190, discountY, { align: 'right' });
  }

  const totalY = finalY + (data.discountPercent > 0 ? 14 : 7);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`${l.total}:`, 110, totalY);
  doc.text(formatHKD(data.total), 190, totalY, { align: 'right' });

  // --- Footer ---
  let footerY = totalY + 15;

  if (data.paymentTerms) {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.text(`${l.paymentTerms}:`, 20, footerY);
    doc.setFont('helvetica', 'normal');
    doc.text(data.paymentTerms, 20, footerY + 5);
    footerY += 12;
  }

  if (data.bankDetails) {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.text(`${l.bankDetails}:`, 20, footerY);
    doc.setFont('helvetica', 'normal');
    doc.text(data.bankDetails, 20, footerY + 5);
    footerY += 12;
  }

  if (data.notes) {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.text(`${l.notes}:`, 20, footerY);
    doc.setFont('helvetica', 'normal');
    doc.text(data.notes, 20, footerY + 5);
  }

  // Page number
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'italic');
    doc.text(
      `${l.page} ${i} ${l.generated}`,
      105,
      290,
      { align: 'center' }
    );
  }

  return doc;
}

export function generatePDFBlob(data: PDFData): Blob {
  const doc = generatePDF(data);
  return doc.output('blob');
}
